### ISSUE TITLE
expandAbbreviation versus pressing tab

### ISSUE THREAD

**Issue by adam-lynch** [emmetio/textarea#1]
Why is expandAbbreviation outputting different HTML to pressing tab? [What's going on here? ](http://jsfiddle.net/2dXaq/)

**Comment by sergeche** [comment]
With `emmet.expandAbbreviation()` you’re just transforming abbreviation while `Expand Abbreviation` action (bound to Tab key) does additional pre/post-processing.

**Comment by adam-lynch** [comment]
So you're saying that during the pre/post-processing, the `${0}` is removed?

**Comment by sergeche** [comment]
It’s not just removed, but located to correctly place caret.

**Comment by adam-lynch** [comment]
Not sure what you mean by that. Is there a convenient method I can call to expand an abbreviation? (With the same output as if I pressed tab in this scenario)

**Comment by sergeche** [comment]
If you just want to get a clean output, you have to call `emmet.expandAbbreviation()` method with second `profile` argument with `"place_cursor": false` option: http://docs.emmet.io/customization/syntax-profiles/

Or take a look at https://github.com/emmetio/emmet/blob/master/plugins/textarea/editor.js#L161

**Comment by adam-lynch** [comment]
Thanks :)
